name: My CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

jobs:

  ############ TESTING PHASE: CI ACTIONS ############

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Download/Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies on ubuntu computer
        run: pip install -r requirements.txt

      - name: Run tests with pytest
        run: python -m pytest -v # this is safer than just 'pytest'

  ############ DEPLOY ON HUB PHASE: CD ACTIONS ############

  deploy:
    runs-on: ubuntu-latest
    needs: [test] # deploy only if tests pass
    steps:

      - name: Download/Checkout code
        uses: actions/checkout@v4

      - name: Login on Docker Hub
        uses: docker/login-action@v3
        with:
          # username and password stored in the repository secrets
          username: ${{secrets.DOCKER_USERNAME}} 
          password: ${{secrets.DOCKER_PASSWORD}}

      # - name: Build Docker image
      #   run: docker build -t my_image:latest .
      # - name: Tag Docker image
      #   run: docker tag my_image:latest ${{secrets.DOCKER_USERNAME}}/my_image:latest
      # - name: Push Docker image
      #   run: docker push ${{secrets.DOCKER_USERNAME}}/my_image:latest

      # the following steps replace the above three steps and are safer
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/machineinnovators_monitoring:latest